services:
  app:
    container_name: springboot
    build:
      context: ..
      dockerfile: ./mesi_backend_rpg/Dockerfile
    command: ["mvn", "spring-boot:run"]
    volumes:
      - backend-data:/app/Backend
      - ~/.m2/repository:/root/.m2/repository
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mesi_rpg
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - network
  db:
    container_name: database
    image: mysql:8.0.19
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mesi_rpg
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "2001:80"
    environment:
      PMA_HOST : db
      PMA_PORTS : 3306
    networks:
      - network
volumes:
  db_data:
  backend-data:
networks:
  network: