app = "mesi-rpg-api"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[env]
  SERVER_ADDRESS = "0.0.0.0"
  SPRING_PROFILES_ACTIVE = "prod"