app = "mesi-backend-rpg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[mounts]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"