app = "mesi-backend-rpg"

[build]
  dockerfile = "Dockerfile"

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  MYSQL_ROOT_PASSWORD = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# Augmenter le délai de vérification de santé
[[services.tcp_checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "60s"

[mounts]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"